# Generated by Django 5.1.6 on 2025-02-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('number', models.CharField(max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(max_length=10)),
                ('insurance_company', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('lead_owner', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
    ]
