# Generated by Django 5.1.6 on 2025-02-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='type',
            new_name='lead_type',
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mrn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], max_length=10),
        ),
    ]
